version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python -m pytest
      - bandit --severity mediu -r app.py
artifacts:
  files:
    - '**/*'
